apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: speedy-trucks-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 50m
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - speedy-trucks.example.com
      secretName: speedy-trucks-tls
  rules:
    - host: www.speedy-trucks.example.com
      http:
        paths:
          - path: /api(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: speedy-trucks-backend
                port:
                  number: 5000
          - path: /(.*)
            pathType: Prefix
            backend:
              service:
                name: speedy-trucks-frontend
                port:
                  number: 80
