apiVersion: v1
kind: Secret
metadata:
  name: speedy-trucks-secrets
type: Opaque
stringData:
  JWT_SECRET: "{{JWT_SECRET}}"
  VITE_GOOGLE_MAPS_API_KEY: "{{VITE_GOOGLE_MAPS_API_KEY}}"
  RAZORPAY_KEY_ID: "{{RAZORPAY_KEY_ID}}"
  RAZORPAY_KEY_SECRET: "{{RAZORPAY_KEY_SECRET}}"
  FCM_SERVER_KEY: "{{FCM_SERVER_KEY}}"
  MONGODB_URI: "{{MONGODB_URI}}"
  GRAFANA_ADMIN_PASSWORD: "{{GRAFANA_ADMIN_PASSWORD}}"
  ALERT_SLACK_WEBHOOK_URL: "{{ALERT_SLACK_WEBHOOK_URL}}"
  ALERT_EMAIL_FROM: "{{ALERT_EMAIL_FROM}}"
  ALERT_EMAIL_SMARTHOST: "{{ALERT_EMAIL_SMARTHOST}}"
  ALERT_EMAIL_AUTH_USERNAME: "{{ALERT_EMAIL_AUTH_USERNAME}}"
  ALERT_EMAIL_AUTH_PASSWORD: "{{ALERT_EMAIL_AUTH_PASSWORD}}"
  ALERT_EMAIL_TO: "{{ALERT_EMAIL_TO}}"
  ALERT_PAGERDUTY_ROUTING_KEY: "{{ALERT_PAGERDUTY_ROUTING_KEY}}"
