import PDFDocument from 'pdfkit';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

export function generateGSTInvoice(invoice, outputPath) {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ size: 'A4', margin: 40 });
      const stream = fs.createWriteStream(outputPath);

      stream.on('error', reject);
      doc.pipe(stream);

      doc.fontSize(20).font('Helvetica-Bold').text('GST Invoice', 50, 50);

      doc.fontSize(10).font('Helvetica').text(`Invoice #: ${invoice.id}`, 50, 100);
      doc.text(`Date: ${invoice.date}`, 50, 115);
      doc.text(`Shipper: ${invoice.shipper}`, 50, 130);

      const y = 180;
      doc.fontSize(12).font('Helvetica-Bold').text('Invoice Details', 50, y);

      const tableTop = y + 30;
      const col1 = 50;
      const col2 = 250;
      const col3 = 400;
      const rowHeight = 25;

      doc.fontSize(10).font('Helvetica-Bold');
      doc.text('Description', col1, tableTop);
      doc.text('Amount', col2, tableTop);
      doc.text('Tax', col3, tableTop);

      doc.font('Helvetica').fontSize(9);
      let currentY = tableTop + rowHeight;

      doc.text('Freight Charge', col1, currentY);
      doc.text(`₹${invoice.value.toLocaleString('en-IN')}`, col2, currentY);
      doc.text('—', col3, currentY);

      currentY += rowHeight;

      doc.text('CGST (9%)', col1, currentY);
      doc.text('—', col2, currentY);
      doc.text(`₹${invoice.cgst.toLocaleString('en-IN')}`, col3, currentY);

      currentY += rowHeight;

      doc.text('SGST (9%)', col1, currentY);
      doc.text('—', col2, currentY);
      doc.text(`₹${invoice.sgst.toLocaleString('en-IN')}`, col3, currentY);

      currentY += rowHeight;

      doc.text('IGST (18%)', col1, currentY);
      doc.text('—', col2, currentY);
      doc.text(`₹${invoice.igst.toLocaleString('en-IN')}`, col3, currentY);

      currentY += rowHeight + 10;
      doc.font('Helvetica-Bold').fontSize(11);
      const total = invoice.value + invoice.cgst + invoice.sgst + invoice.igst;
      doc.text('Total Amount:', col1, currentY);
      doc.text(`₹${total.toLocaleString('en-IN')}`, col3, currentY);

      doc.fontSize(9).font('Helvetica').text(`Status: ${invoice.status}`, 50, currentY + 40);
      doc.text(`HSN Code: ${invoice.hsn}`, 50, currentY + 55);

      doc.text('Generated by Speedy Trucks (aptrucking.in)', 50, currentY + 100);
      doc.text('This is a digitally generated invoice.', 50, currentY + 115);

      doc.end();

      stream.on('finish', () => {
        resolve(outputPath);
      });
    } catch (error) {
      reject(error);
    }
  });
}
